# Generated by Django 4.2.16 on 2025-03-07 12:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('site_location', models.CharField(max_length=200)),
                ('site_name', models.CharField(max_length=100)),
                ('project_start_date', models.DateField()),
                ('project_end_date', models.DateField()),
                ('project_duration', models.IntegerField(editable=False, null=True)),
                ('documents', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectsite.client')),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('due_date', models.DateField()),
                ('completed', models.CharField(choices=[('C', 'Completed'), ('NC', 'Not Completed'), ('P', 'Pending')], default='P', max_length=2)),
                ('progress', models.IntegerField(default=0)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('stage_type', models.CharField(choices=[('ceiling', 'Ceiling'), ('flooring', 'Flooring'), ('plumbing', 'Plumbing'), ('painting', 'Painting'), ('foundation', 'Foundation'), ('framing', 'Framing'), ('electrical', 'Electrical'), ('hvac', 'HVAC'), ('roofing', 'Roofing'), ('drywall', 'Drywall'), ('insulation', 'Insulation'), ('siding', 'Siding'), ('windows', 'Windows'), ('doors', 'Doors'), ('landscaping', 'Landscaping'), ('finishing', 'Finishing'), ('furniture_installation', 'Furniture Installation'), ('final_touchups', 'Final Touch-ups')], max_length=50)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectsite.project')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('amount_spent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectsite.project')),
            ],
        ),
    ]
