# Generated by Django 4.2.16 on 2025-03-12 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectsite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stage',
            name='hours_logged',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='stage',
            name='milestones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stage',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('on_hold', 'On Hold')], default='not_started', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='client',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='stage',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='projectsite.project'),
        ),
    ]
