# Generated by Django 4.2.16 on 2025-03-12 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectsite', '0002_stage_comments_stage_hours_logged_stage_milestones_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectsite.client'),
        ),
    ]
