# Generated by Django 4.2.16 on 2025-03-12 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectsite', '0003_alter_project_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stage',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='stage',
            name='hours_logged',
        ),
        migrations.RemoveField(
            model_name='stage',
            name='milestones',
        ),
        migrations.RemoveField(
            model_name='stage',
            name='status',
        ),
    ]
