# Generated by Django 4.2.20 on 2025-03-13 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectsite', '0005_alter_expense_options_expense_stage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=models.TextField(),
        ),
    ]
