# Generated by Django 4.2.16 on 2025-03-18 02:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projectsite', '0007_alter_client_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='completed',
            field=models.CharField(choices=[('C', 'Completed'), ('NC', 'Not Completed'), ('P', 'Pending')], default='P', max_length=50),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('Team User', 'Team User'), ('Client', 'Client')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
