# Generated by Django 4.2.16 on 2025-03-18 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectsite', '0008_alter_stage_completed_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
