# Generated by Django 4.2.16 on 2025-03-20 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectsite', '0012_alter_expense_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stage',
            name='completed',
        ),
        migrations.AddField(
            model_name='stage',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('on_hold', 'On Hold')], default='not_started', max_length=20),
        ),
    ]
