# Generated by Django 4.2.20 on 2025-03-21 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectsite', '0013_remove_stage_completed_stage_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='breadth',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Breadth (feet)'),
        ),
        migrations.AddField(
            model_name='project',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Length (feet)'),
        ),
        migrations.AddField(
            model_name='project',
            name='total_land_area',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10, null=True, verbose_name='Total Land Area (sq ft)'),
        ),
    ]
