# Generated by Django 4.2.20 on 2025-03-23 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectsite', '0014_project_breadth_project_length_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='total_land_area',
            new_name='original_land_area',
        ),
    ]
