# Generated by Django 4.2.20 on 2025-03-23 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectsite', '0015_rename_total_land_area_project_original_land_area'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='original_land_area',
            new_name='total_land_area',
        ),
    ]
