# Generated by Django 4.2.16 on 2025-03-24 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectsite', '0016_rename_original_land_area_project_total_land_area'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='total_land_area',
            new_name='land_area',
        ),
    ]
