# Generated by Django 4.2.16 on 2025-03-24 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectsite', '0017_rename_total_land_area_project_land_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='land_area',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Total Land Area (sq ft)'),
        ),
    ]
