# Generated by Django 4.2.20 on 2025-03-19 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('CLIENT', 'Client'), ('TEAM_USER', 'Team User')], default='CLIENT', max_length=20),
        ),
    ]
